### ISSUE TITLE
Moleculer retryPolicy doesn't work inside queues

### ISSUE THREAD

**Issue by dabibu153** [moleculerjs/moleculer-addons#110]
Unlike broker calls made inside actions, the retryPloicy doesn't apply to the calls made within queue logic (moleculer-bull)

In my current implementation, I am attempting to handle any failed action calls with a try-catch block. It works fine but I am hoping to give my action calls some leeway in case the target service is experiencing a short downtime ( like hot-reloads).

I was wondering if it's possible to enforce the core molecular retry logic inside queues.

**Comment by icebob** [comment]
No, because they are different modules. The queue addons always have an internal lib which solves the queueing logic. Moleculer retryPolicy is used in internal Moleculer functions, like action calls.
