### ISSUE TITLE
Cannot pull package neither with yarn nor npm

### ISSUE THREAD

**Issue by SandorHegedus-KOD** [moleculerjs/moleculer-addons#119]
Hi!

I am trying to add this package to our project with yarn but have no luck.
I tried with npm as well:
![image](https://user-images.githubusercontent.com/110170657/201525315-c2bdb7bf-5d9e-4aca-a6b0-69a473a5a576.png)

I can install other packages so probably not a global npm problem.

Thanks!

**Comment by SandorHegedus-KOD** [comment]
the problem was that package name was not correct on the npm site:

NOK: npm install moleculer-pqsl-queue
OK: npm install moleculer-psql-queue

**Comment by icebob** [comment]
@AndreMaz could you fix it plz in the readme?

![image](https://user-images.githubusercontent.com/306521/202894991-cf000428-5943-4f21-b765-786de4a24513.png)
