### ISSUE TITLE
Mailer not working in production

### ISSUE THREAD

**Issue by molobala** [moleculerjs/moleculer-addons#23]
I have a trouble using mailer service, I get RequestTimeout when calling `mailer.send`.  
In developpement it works good but not on my server.

Here my mailer mixin service
```
module.exports = {
  name: 'mailer',
  mixins: [Mailer],
  settings: {
    //from: 'doumbiamahamadou.sam@gmail.com',
    transport: {
      //host: `${process.env.SMTP_HOST}`,
      service: 'mailgun',
      auth: {
        api_key: `${process.env.GUN_API_KEY}`,
        domain: `${process.env.GUN_DOMAIN}`,
      }
    }
  },
  created(){
    //console.log(this.settings);
  }
}
```
And when I call

```
let html = `
         .....
        `
      console.log(await this.broker.call('mailer.send', {
        subject: `.......`,
        to: ws.owner.email,
        html
      },{
          retry: 5,
      }));
```
Any Idea ?

**Comment by icebob** [comment]
I have no idea. I'm using it in production and I have no problem with it.

**Comment by molobala** [comment]
I don't exactly understand what was wrong, but I think that moleculer-mailer does not work with Mail Gun (using API key and domain).  
My understanding is that line https://github.com/moleculerjs/moleculer-addons/blob/17efa8dc6e1d3a6a0731c0dcc1232d2868569826/packages/moleculer-mail/src/index.js#L172 
That line will create just SMTP transporter, so we need to use an extra plugin to possibly create a transporter for other than SMTP.  
When I use mailgun-js everything is going well :).

**Comment by icebob** [comment]
My working code is:

```js
"use strict";

const MailService = require("moleculer-mail");

module.exports = {
	name: "mail",
	mixins: [MailService],
	settings: {
		from: "hello@example.com",
		transport: {
			service: "mailgun",
			auth: {
				user: process.env.MAILGUN_USER,
				pass: process.env.MAILGUN_PASS
			}
		}
	}
};
```

**Comment by molobala** [comment]
SMTP works fine using moleculer-mail in local, and timeout on my server, but using mailgun API , its not working nor in local nor on server I'm getting that 

```
Unable to send email:  { Error: Missing credentials for "PLAIN"
```
My actual code which works with API  
```
const Mailer = require('moleculer-mail');
const nodemailer = require('nodemailer');
const mailgun = require('mailgun-js')

//create a service and use Malier as a mixins
module.exports = {
  name: 'mailer',
  transporter : null,
  //mixins: [Mailer],
  settings: {
    from: `${process.env.MAIL_FROM}`,
    transport: {
      auth: {
        apiKey: `${process.env.GUN_API_KEY}`,
        domain: `${process.env.GUN_DOMAIN}`,
      }
    }
  },
  actions:{
    /**
     * Send an email to recipients
     */
    send: {
      handler(ctx) {
        return new Promise((resolve,reject)=>{
           if(!ctx.params.from){
            ctx.params.from = this.settings.from || '';
           }
           console.log("Sending mail from "+ctx.params.from+" to "+ctx.params.to);
           this.transporter.messages().send(ctx.params, (err,body)=>{
            if(err) return reject(err);
            console.log(body);
            return resolve(body);
           });
        })
      }
    }
  },

  /**
   * Service created lifecycle event handler
   */
  created() {
   this.transporter = mailgun(this.settings.transport.auth);
   //console.log(this.transporter);
  },
}

```

**Comment by icebob** [comment]
Which version do you use local and on server? Maybe I put a bug in the last release.

**Comment by molobala** [comment]
No I don't think, since  I have the same versioon both (version 1.1.1) . Probably a problem with my server, since it works in local.

**Comment by icebob** [comment]
But what is it in your package.json? `^1.1.1` or `~1.1.1`, or `1.1.1`? First of them will install the latest `1.2.0` version instead of `1.1.1`.

**Comment by molobala** [comment]
I have `^1.1.1` in my package json  

AH I see, so I will try jus `1.1.1` and see what it will give

**Comment by molobala** [comment]
Nope, the same problem when using `"moleculer-mail": "1.1.1"` .

**Comment by icebob** [comment]
Any updated? Problem is solved?
