### ISSUE TITLE
Redis connection to 127.0.0.1:6379 failed

### ISSUE THREAD

**Issue by xeroxstar** [moleculerjs/moleculer-addons#36]
Hello, why do i get this error when i create a task: 

`UnhandledPromiseRejectionWarning: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379` ? I dont have redis server!

**UPDATE**: i got the answer from bee-queue npm ,you can close it. thx

**Comment by sun1211** [comment]
So How do we fix it?
